export * from './httpUser.controller'
export * from './httpUpload.controller'
export * from './httpAuthentication.admin.controller'
export * from './httpVoice.controller'
export * from './httpAttendance.controller'
export * from './httpChat.controller'
export * from './httpWebSocket.controller'
export * from './httpHome.controller'
